# Generated by Django 3.0.6 on 2020-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashdeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashdeal',
            name='summary',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
